version: 2


build:
  os: ubuntu-22.04

  tools:
    python: "3.10"

  apt_packages:
    - python3-gi
    - python3-gi-cairo
    - gir1.2-gtk-3.0


python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .


sphinx:
  configuration: docs/conf.py


formats:
  - pdf
  - epub


    # vi: tabstop=2 shiftwidth=2 softtabstop=2
